global:
  scrape_interval: 15s

scrape_configs:
  - job_name: node
    static_configs:
      - targets:
        - node_exporter:9100

remote_write:
  - url: http://host.containers.internal:11050/v1/prometheus/write?db=public
